src/Samples/Sample.AspNetCore/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Sample.AspNetCore.Models;

public class Product
{
    public string Class { get; set; }
    public string ImageUrl { get; set; }
    public string ItemUrl { get; set; }
    public string Name { get; set; }

    [Required(ErrorMessage = "Please provide a number greater than zero!")]
    [Display(Name = "Unit price")]
    [Range(1, int.MaxValue)]
    public decimal Price { get; set; }

    public int ProductId { get; set; }
    public string Reference { get; set; }
    public string Type { get; set; }

    public int VatPercentage { get; set; }
}

src/Samples/Sample.AspNetCore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;

using Sample.AspNetCore.Models;

namespace Sample.AspNetCore.Components;

public class CartSummaryViewComponent : ViewComponent
{
    private readonly Cart _cart;


    public CartSummaryViewComponent(Cart cartService)
    {
        _cart = cartService;
    }


    public IViewComponentResult Invoke()
    {
        return View(_cart);
    }
}

src/Samples/Sample.AspNetCore/Controllers/CartController.cs
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Sample.AspNetCore.Data;
using Sample.AspNetCore.Models;

namespace Sample.AspNetCore.Controllers;

public class CartController : Controller
{
    private readonly Cart _cartService;
    private readonly StoreDbContext _storesContext;


    public CartController(StoreDbContext storeDb, Cart cart)
    {
        _storesContext = storeDb;
        _cartService = cart;
    }


    public async Task<IActionResult> AddToCart(int id)
    {
        var productList = await _storesContext.Products.ToListAsync();
        var product = productList.FirstOrDefault(p => p.ProductId == id);
        _cartService.AddItem(product, 1);

        return RedirectToAction("Index", "Products");
    }


    [HttpPost]
    public IActionResult Create(Cart cart)
    {
        if (ModelState.IsValid)
        {
            return RedirectToAction("Index", "Payment", cart);
        }

        return View(cart);
    }


    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }


    public IActionResult Index()
    {
        return View();
    }


    public IActionResult Privacy()
    {
        return View();
    }


    public IActionResult RemoveFromCart(int id)
    {
        var line = _cartService.CartLines.FirstOrDefault(i => i.Product.ProductId == id);
        if (line != null)
        {
            _cartService.RemoveItem(line.Product, line.Quantity);
        }

        return RedirectToAction("Index", "Products");
    }


    [HttpPost]
    public IActionResult UpdateQuantity(int id, int quantity)
    {
        var line = _cartService.CartLines.FirstOrDefault(i => i.Product.ProductId == id);
        if (line != null)
        {
            line.Quantity = quantity;
            _cartService.Update();
        }

        return RedirectToAction("Index", "Products");
    }
}

src/Samples/Sample.AspNetCore/Controllers/ProductsController.cs
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using Sample.AspNetCore.Data;
using Sample.AspNetCore.Models;

namespace Sample.AspNetCore.Controllers;

public class ProductsController : Controller
{
    private readonly StoreDbContext _storeDbContext;


    public ProductsController(StoreDbContext storeDbStoreDbContext)
    {
        _storeDbContext = storeDbStoreDbContext;
    }


    // GET: Products/Create
    public IActionResult Create()
    {
        return View();
    }


    // POST: Products/Create
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,Name,Reference,ImageUrl,ItemUrl,Type,Class,Price")]
        Product product)
    {
        if (ModelState.IsValid)
        {
            _storeDbContext.Add(product);
            await _storeDbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        return View(product);
    }


    // POST: Products/Delete/5
    [HttpPost]
    [ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var product = await _storeDbContext.Products.FindAsync(id);
        _storeDbContext.Products.Remove(product);
        await _storeDbContext.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }


    // GET: Products/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var product = await _storeDbContext.Products.FirstOrDefaultAsync(m => m.ProductId == id);
        if (product == null)
        {
            return NotFound();
        }

        return View(product);
    }


    // GET: Products/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var product = await _storeDbContext.Products.FindAsync(id);
        if (product == null)
        {
            return NotFound();
        }

        return View(product);
    }


    // POST: Products/Edit/5
    // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
    // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id,
        [Bind("Id,Name,Reference,ImageUrl,ItemUrl,Type,Class,Price")]
        Product product)
    {
        if (id != product.ProductId)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _storeDbContext.Update(product);
                await _storeDbContext.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(product.ProductId))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToAction(nameof(Index));
        }

        return View(product);
    }


    // GET: Products
    public async Task<IActionResult> Index()
    {
        return View(await _storeDbContext.Products.ToListAsync());
    }


    private bool ProductExists(int id)
    {
        return _storeDbContext.Products.Any(e => e.ProductId == id);
    }
}

src/Samples/Sample.AspNetCore/Views/Products/Create.cshtml
@model Product

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Product</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reference" class="control-label"></label>
                <input asp-for="Reference" class="form-control"/>
                <span asp-validation-for="Reference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control"/>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemUrl" class="control-label"></label>
                <input asp-for="ItemUrl" class="form-control"/>
                <span asp-validation-for="ItemUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control"/>
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/Samples/Sample.AspNetCore/Views/Products/Delete.cshtml
@model Product

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ItemUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ItemUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId"/>
        <input type="submit" value="Delete" class="btn btn-danger"/> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

src/Samples/Sample.AspNetCore/Views/Products/Details.cshtml
@model Product

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Reference)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Reference)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ItemUrl)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ItemUrl)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Class)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Class)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

src/Samples/Sample.AspNetCore/Views/Products/Edit.cshtml
@model Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId"/>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Reference" class="control-label"></label>
                <input asp-for="Reference" class="form-control"/>
                <span asp-validation-for="Reference" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageUrl" class="control-label"></label>
                <input asp-for="ImageUrl" class="form-control"/>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ItemUrl" class="control-label"></label>
                <input asp-for="ItemUrl" class="form-control"/>
                <span asp-validation-for="ItemUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Class" class="control-label"></label>
                <input asp-for="Class" class="form-control"/>
                <span asp-validation-for="Class" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

src/Samples/Sample.AspNetCore/Views/Products/Index.cshtml
@using System.Globalization
@model IEnumerable<Product>
@inject Cart CartService
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["AbortMessage"] != null)
{
    <div class="alert" data-automation="paymentorderlink">@TempData["PaymentOrderLink"]</div>
    <div class="alert alert-success">@TempData["AbortMessage"]</div>
}
else if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-warning">@TempData["ErrorMessage"]</div>
}
<h1>Store</h1>

<p>
    <a asp-action="Create">Create New Product</a>
</p>
<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Reference)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Class)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Reference)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Class)
            </td>
	        <td>
                @item.Price.ToString("c", CultureInfo.CreateSpecificCulture("sv-SE"))
	        </td>
            <td>
                @*<a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> |*@
                <a class="btn btn-primary" data-automation="button-addtocart" asp-action="AddToCart" asp-controller="Cart" asp-route-id="@item.ProductId">Add to Cart</a>
            </td>
        </tr>
    }
    </tbody>
</table>
@if (CartService.CartLines.Any())
{
    @await Component.InvokeAsync("CartSummary")
}